FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc curl && rm -rf /var/lib/apt/lists/*

COPY /requirements/requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY api.py .

RUN useradd -m appuser
USER appuser

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]